[build]
target = 'x86_64-pc-windows-msvc'

[target.x86_64-pc-windows-msvc]
linker = "lld"
rustflags = [
  "-Lnative=D:/.xwin/crt/lib/x86_64",
  "-Lnative=D:/.xwin/sdk/lib/um/x86_64",
  "-Lnative=/home/username/.xwin/sdk/lib/ucrt/x86_64"
]

[target.aarch64-linux-android]
linker = 'D:\androidSdk\ndk\25.0.8775105\toolchains/llvm/prebuilt/windows-x86_64\bin\aarch64-linux-android24-clang.cmd'
rustflags = [
    '-L',
    'E:\pnpm-demo\yx-blog\src-tauri/.cargo',
    '-Clink-arg=-landroid',
    '-Clink-arg=-llog',
    '-Clink-arg=-lOpenSLES',
]

[target.armv7-linux-androideabi]
linker = 'D:\androidSdk\ndk\25.0.8775105\toolchains/llvm/prebuilt/windows-x86_64\bin\armv7a-linux-androideabi24-clang.cmd'
rustflags = [
    '-L',
    'E:\pnpm-demo\yx-blog\src-tauri/.cargo',
    '-Clink-arg=-landroid',
    '-Clink-arg=-llog',
    '-Clink-arg=-lOpenSLES',
]

[target.i686-linux-android]
linker = 'D:\androidSdk\ndk\25.0.8775105\toolchains/llvm/prebuilt/windows-x86_64\bin\i686-linux-android24-clang.cmd'
rustflags = [
    '-L',
    'E:\pnpm-demo\yx-blog\src-tauri/.cargo',
    '-Clink-arg=-landroid',
    '-Clink-arg=-llog',
    '-Clink-arg=-lOpenSLES',
]

[target.x86_64-linux-android]
linker = 'D:\androidSdk\ndk\25.0.8775105\toolchains/llvm/prebuilt/windows-x86_64\bin\x86_64-linux-android24-clang.cmd'
rustflags = [
    '-L',
    'E:\pnpm-demo\yx-blog\src-tauri/.cargo',
    '-Clink-arg=-landroid',
    '-Clink-arg=-llog',
    '-Clink-arg=-lOpenSLES',
]
